// <auto-generated />
using GroceryFinder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceryFinder.Migrations
{
    [DbContext(typeof(GroceryFinderContext))]
    [Migration("20200403170024_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GroceryFinder.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("CloseHour");

                    b.Property<bool>("Delivery");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("OpenHour");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            City = "Beaverton",
                            CloseHour = 22,
                            Delivery = false,
                            Description = "Provides some services like ordering your groceries online and at-store pickup where they load the groceries in your car for you. The store is taking precautions to maintain social distancing with tape marking people's positions to stand while they wait in line for checkout. Cashiers wear masks.",
                            Name = "FredMeyers",
                            OpenHour = 7
                        },
                        new
                        {
                            StoreId = 2,
                            City = "Beaverton",
                            CloseHour = 22,
                            Delivery = false,
                            Description = "Provides some services like ordering your groceries online and at-store pickup where they load the groceries in your car for you. The store is taking precautions to maintain social distancing with tape marking people's positions to stand while they wait in line for checkout. Cashiers wear masks.",
                            Name = "Winco",
                            OpenHour = 7
                        },
                        new
                        {
                            StoreId = 3,
                            City = "Beaverton",
                            CloseHour = 19,
                            Delivery = false,
                            Description = "The store is taking precautions to maintain social distancing with tape marking people's positions to stand while they wait in line for checkout. Cashiers wear masks.",
                            Name = "Trader Joe's",
                            OpenHour = 9
                        },
                        new
                        {
                            StoreId = 4,
                            City = "Beaverton",
                            CloseHour = 21,
                            Delivery = false,
                            Description = "Provides some services like ordering your groceries online and at-store pickup where they load the groceries in your car for you. The store is taking precautions to maintain social distancing with tape marking people's positions to stand while they wait in line for checkout. Cashiers wear masks.",
                            Name = "Grocery Outlet",
                            OpenHour = 8
                        },
                        new
                        {
                            StoreId = 5,
                            City = "Beaverton",
                            CloseHour = 20,
                            Delivery = false,
                            Description = "Provides some services like ordering your groceries online and at-store pickup where they load the groceries in your car for you. The store is taking precautions to maintain social distancing with tape marking people's positions to stand while they wait in line for checkout. Cashiers wear masks.",
                            Name = "New Seasons",
                            OpenHour = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
